version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - vendor:/app/vendor
    environment:
      - API_LAYER_EXCHANGE_RATES_API_KEY=${API_LAYER_EXCHANGE_RATES_API_KEY}

  test:
    build: .
    volumes:
      - .:/app
      - vendor:/app/vendor
    command: ./vendor/bin/pest

volumes:
  vendor:
